### ISSUE TITLE
Beanstalkd queue with multiple tubes supported?

### ISSUE THREAD

**Issue by jmirandase** [juriansluiman/SlmQueueBeanstalkd#57]
Hi @bakura10,

I apologise if this is not the proper channel to ask this question but I would like to know if this module supports having multiple tubes per queue. I did not find any hint on that in the documentation and from what I can infer from the code I think only a tube per queue is supported, is that right?

Thanks,
JM

**Comment by bakura10** [comment]
@basz im not an expert on this topic and I do not really remember (im on holiday right now so hard to check the code). If I remember you know a bit better beanstalkd?

**Comment by basz** [comment]
no. sorry, never used beanstalk.
